# Upload some file
POST http://localhost:3333/api/files/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="file.http"

< ./file.http
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###

### curl -i -F file="@/C:/avatars/avatar-angelina.jpg" http://localhost:3337/api/files/upload/avatar/64288cdee77d1de6e8d15b7e

### curl -i -F file="@/C:/avatars/avatar-max.jpg" http://localhost:3337/api/files/upload/image/1

###

# Get file by ID
GET http://localhost:3333/api/files/643ce69f6fd7fc73120410c1 HTTP/1.1

###
