# 1.3. Создание новых публикаций в блоге #Примеры вызовов  ниже
POST http://localhost:4000/api/post/create HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDQzZjZjOTdhMDQ2YzNiOGY3NWFmNDUiLCJlbWFpbCI6InVzZXIxMEBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiJ1c2VyIiwidXNlck5hbWUiOiJLZWtzMyIsImlhdCI6MTY4MzY1MDkzNSwiZXhwIjoxNjgzNjUxNTM1fQ.F-qmlQdnLyoxhwWxPzd0nOLc_r2bjj-Zlk1Az_GLywo
Content-Type: application/json

{
  "content": "http://gg.com",
  "addInfo": "Описание (опционально). Описание ссылки",
  "tags": ["Link"],
  "postType": "Link",
  "isRepost": false
}
###

###1.7. Загрузка изображений для публикации в блоге.
###curl -i -H 'Accept: application/json' -H "Authorization: TOKEN " -F file="@/C:/avatars/avatar-max.jpg" http://localhost:4000/api/files/image/5


# 1.4. Просмотр детальной информации о публикации
GET http://localhost:4000/api/post/1 HTTP/1.1
Content-Type: application/json
###


###
# 1.6. Удаление публикаций в блоге
DELETE  http://localhost:4000/api/post/delete/9 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDVhNTEyMDdiYTA0M2ZmZGFiYTA1MjQiLCJlbWFpbCI6InVzZXI2NkBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiJ1c2VyIiwidXNlck5hbWUiOiJVc2VyTmV3IiwiaWF0IjoxNjgzNjQzODA4LCJleHAiOjE2ODM2NDQ0MDh9.O8FHzKQWTau6ffTbNLN84CI-ToMTp4ll64H7m8rKDpU
Content-Type: application/json
###

# 1.5. Редактирование публикаций в блоге
PATCH  http://localhost:4000/api/post/edit/4 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDI4Nzg5MDE5ODkxNGU4ODVjOTBmNTQiLCJlbWFpbCI6InVzZXJAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoidXNlciIsInVzZXJOYW1lIjoiS2VrczEiLCJpYXQiOjE2ODM2NTI5NjksImV4cCI6MTY4MzY1MzU2OX0.9VnLeVU6XB6oglG_jh5Cw6gqa8HfZZ8Sk7fITDq1ed8
Content-Type: application/json

{
  "title": "Новое название для публикации 4",
  "postType": "Link",
  "postState": "Public"
}

###
#  1.13. Репост публикаций
POST  http://localhost:4000/api/post/repost/3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDVhNTEyMDdiYTA0M2ZmZGFiYTA1MjQiLCJlbWFpbCI6InVzZXI2NkBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiJ1c2VyIiwidXNlck5hbWUiOiJVc2VyTmV3IiwiaWF0IjoxNjgzNjQ1OTk0LCJleHAiOjE2ODM2NDY1OTR9.FwSA0vEPwCLyUAxT4_n2zYjoNkDcTtUHwhqKXVemvAk
Content-Type: application/json

###


# 1.12. Получение списка публикаций с применением сортировки: по популярности, дате создания, по количеству лайков, по количеству комментариев.
GET http://localhost:4000/api/posts?user=645a51207ba043ffdaba0524&sortDirection=desc&sortComments=desc&limit=15&page=1 HTTP/1.1

###

# Get draft posts bu User
GET http://localhost:4000/api/posts/draft HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDQzZjZjOTdhMDQ2YzNiOGY3NWFmNDUiLCJlbWFpbCI6InVzZXIxMEBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiJ1c2VyIiwidXNlck5hbWUiOiJLZWtzMyIsImlhdCI6MTY4MzI5NjcyOSwiZXhwIjoxNjgzMjk3MzI5fQ.a9Au4CNk1DQcVRGX0ZP--XmSAJbgWVv2NvNNz3axsaY
Content-Type: application/json
###

# 1.17. Поиск публикаций по названию.
GET http://localhost:4000/api/posts/title/Заголовок  HTTP/1.1
Content-Type: application/json
###




###
{
  "title": "Заголовок для публикации  Видео",
  "content": "www.youtube.com/watch?v=88",
  "tags": ["Video"],
  "postType": "Video",
  "isRepost": false
}
###
{
  "title": " Заголовок для публикации - Текст",
  "content": "Текст публикации Текст публикации  Текст публикации Текст публикации Текст публикации Текст публикации Текст публикации",
  "addInfo": "Анонс публикации Анонс публикации Анонс публикации Анонс публикации",
  "tags": ["Text1", "Text2"],
  "postType": "Text",
  "isRepost": false
}
###
{
  "content": "Текст цитаты Текст цитаты Текст цитаты",
  "addInfo": "Текст цитаты",
  "tags": ["Text1", "Quote"],
  "postType": "Quote",
  "isRepost": false
}

### Photo - изображение загружается отдельно
{
  "tags": ["Images"],
  "postType": "Photo",
  "isRepost": false
}
###
{
  "content": "http://gg.com",
  "addInfo": "Описание (опционально). Описание ссылки",
  "tags": ["Link"],
  "postType": "Link",
  "isRepost": false
}
###
