# Create a new user
POST http://localhost:4000/api/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "user66@notfound.local",
  "userName": "UserNew",
  "password": "1234567"
}

###
# Login user by email and password
POST http://localhost:4000/api/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "user66@notfound.local",
  "password": "1234567"
}


###
# Get user by ID
GET http://localhost:4000/api/users/6454b277f6a8413b8a2704b9 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDU0YjI3N2Y2YTg0MTNiOGEyNzA0YjkiLCJlbWFpbCI6InVzZXJOZXcyQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6InVzZXIiLCJ1c2VyTmFtZSI6IlVzZXJOZXciLCJpYXQiOjE2ODM0ODM4MjgsImV4cCI6MTY4MzQ4NDQyOH0.YHr-0TAhUXXNLihDnjbuSot0R1A5NDzsuNw4RhUAnm4
###


# Get new JWT pair
POST http://localhost:4000/api/users/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDU0YjI3N2Y2YTg0MTNiOGEyNzA0YjkiLCJlbWFpbCI6InVzZXJOZXcyQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6InVzZXIiLCJ1c2VyTmFtZSI6IlVzZXJOZXciLCJ0b2tlbklkIjoiYmI4MmIyODMtZDgwMy00MTZkLWE4NWEtOTY4MDM0OWQxNGVjIiwiaWF0IjoxNjgzMjcyMzc0LCJleHAiOjE2ODU4NjQzNzR9.Mv8PUoYMFIY_PEOmo2xUktwGkBl_abSvrN9K6AOABLs

###

# Change password
POST http://localhost:4000/api/users/changepassword HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDU0YjI3N2Y2YTg0MTNiOGEyNzA0YjkiLCJlbWFpbCI6InVzZXJOZXcyQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6InVzZXIiLCJ1c2VyTmFtZSI6IlVzZXJOZXciLCJpYXQiOjE2ODMzNjQ3OTAsImV4cCI6MTY4MzM2NTM5MH0.gRRNF6NHjqJ5jNU1ch69P9qU2C4-d53bG0AqeL68RS8
Content-Type: application/json

{
  "currentPassword": "123456789",
  "newPassword": "12345678910"
}

###

# Create a new subscription
POST http://localhost:4000/api/users/subscription/create HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDU1MjNlNDJjN2NmODAyZjRlMDBhMTMiLCJlbWFpbCI6InVzZXJOZXcyNUBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiJ1c2VyIiwidXNlck5hbWUiOiJVc2VyTmV3IiwiaWF0IjoxNjgzNDgyOTE5LCJleHAiOjE2ODM0ODM1MTl9.T-yxWicUPqwY4SfnOs7tUI8fsAfBKFpWqO0vpEYNjkc
Content-Type: application/json

{
  "userSubscriptionId": "6454b277f6a8413b8a2704b9"
}

###

# Delete subscription by UserID
DELETE  http://localhost:4000/api/users/subscription/delete HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDU1MjNlNDJjN2NmODAyZjRlMDBhMTMiLCJlbWFpbCI6InVzZXJOZXcyNUBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiJ1c2VyIiwidXNlck5hbWUiOiJVc2VyTmV3IiwiaWF0IjoxNjgzNDgzODA0LCJleHAiOjE2ODM0ODQ0MDR9.7sicweE9LYk_hKA5KxX84Zk5FTYyWL_D3EIaqcBY56U
Content-Type: application/json

{
  "userSubscriptionId": "6454b277f6a8413b8a2704b9"
}
###
# Get new posts
GET http://localhost:4000/api/users/notify/newposts HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDU1MjNlNDJjN2NmODAyZjRlMDBhMTMiLCJlbWFpbCI6InVzZXJOZXcyNUBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiJ1c2VyIiwidXNlck5hbWUiOiJVc2VyTmV3IiwiaWF0IjoxNjgzNTM2MTkyLCJleHAiOjE2ODM1MzY3OTJ9.hAcUf2pohvCRvD4QSnbNYPpglqNzdNDtyh_c47rM3qY
Content-Type: application/json

###
