# Create a new subscription
POST http://localhost:3333/api/subscription/create HTTP/1.1
Content-Type: application/json

{
  "userId": "643cef614201d080cdd2ad6e",
  "userSubscriptionId": "6443f6c97a046c3b8f75af45"
}

###

# Get subscription by UserID
GET http://localhost:3333/api/subscription/user/64288ca35d94fcde06acffb3 HTTP/1.1
Content-Type: application/json


###

# Get subscription by userSubscriptionId
GET http://localhost:3333/api/subscription/usersubscription/2 HTTP/1.1
Content-Type: application/json


###

# Delete subscription by UserID
DELETE  http://localhost:3333/api/subscription/delete HTTP/1.1
Content-Type: application/json

{
  "userId": "2",
  "userSubscriptionId": "3"
}
###
