# Create a new post
POST http://localhost:3334/api/post/create HTTP/1.1
Content-Type: application/json

{
  "title": " Валидная ссыки валидности ссылки",
  "content": "http://gg.com",
  "addInfo": "ggg",
  "tags": ["t4t", "ooo","ghghg","T5T", "oyo", "nature","ghghg","hhh"],
  "postType": "Link",
  "isRepost": false,
  "userId": "1"
}

###

# Get post by ID
GET http://localhost:3334/api/post/35 HTTP/1.1
Content-Type: application/json
###

# Delete post by ID
DELETE  http://localhost:3334/api/post/delete/3 HTTP/1.1
Content-Type: application/json
###

# Update post
PATCH  http://localhost:3334/api/post/edit/22 HTTP/1.1
Content-Type: application/json

{
  "title": " Валидная ссыки валидности ссылки",
  "content": "http://gg.com",
  "addInfo": "ggg",
  "tags": [1, 2],
  "postType": "Text",
  "postState": "Public",
  "isRepost": false,
  "userId": "1"
}

###
#  Repost by ID
POST  http://localhost:3334/api/post/repost/5 HTTP/1.1
Content-Type: application/json

{
 "newUserId": "9999"
}
###
