# Create a new post
POST http://localhost:3333/api/post/create HTTP/1.1
Content-Type: application/json

{
  "title": "Title2",
  "video": "video/1.mp3",
  "tags": [1, 2],
  "postType": "Video",
  "postState": "public",
  "isRepost": false,
  "userId": "1"
}

###

# Get post by ID
GET http://localhost:3333/api/post/10 HTTP/1.1
Content-Type: application/json
###

# Get post by TITLE
GET http://localhost:3333/api/post/title/Title2 HTTP/1.1
Content-Type: application/json
###

# Delete post by ID
DELETE  http://localhost:3333/api/post/delete/9 HTTP/1.1
Content-Type: application/json
###

# Update post
PATCH  http://localhost:3333/api/post/edit/10 HTTP/1.1
Content-Type: application/json

{
  "title": "Title 21",
  "video": "video/1.mp3",
  "tags": [1],
  "postType": "Video",
  "postState": "Public",
  "isRepost": false,
  "userId": "1"
}

###
#  Repost by ID
POST  http://localhost:3333/api/post/repost/15 HTTP/1.1
Content-Type: application/json

{
 "userId": "88"
}
###
