# 1.8. Комментирование публикаций в блоге
POST http://localhost:3335/api/comment/create/15 HTTP/1.1
Content-Type: application/json

{
  "message": "ttttttttttt",
  "userId": "555"
}

###

# Список комментариев к блогу
GET http://localhost:3335/api/comment/1?&limit=5&page=1 HTTP/1.1
Content-Type: application/json
###



# Удаление комментария
DELETE  http://localhost:3335/api/comment/delete/1 HTTP/1.1
Content-Type: application/json

{
  "userId": "555"
}
###
